### ISSUE TITLE
Error in worker: Exception: TypeError: types is undefined (https://people.mozilla.org/~bgirard/cleopatra/js/parserWorker.js:1002)

### ISSUE THREAD

**Issue by wilsonpage** [mozilla/cleopatra#32]
After uploading my profile I'm getting the following error:

```
Error in worker: Exception: TypeError: types is undefined (https://people.mozilla.org/~bgirard/cleopatra/js/parserWorker.js:1002)
```

Can provide profile if necessary.

**Comment by bgirard** [comment]
As discussed on IRC, this is an unfortunate regression that is fixed by updating the gecko that's collecting the profile. Also this is the wrong fork of cleopatra. Perhaps we should delete this one.

https://bugzilla.mozilla.org/show_bug.cgi?id=1209779
